{% set name = "enaml-extensions" %}
{% set version = "0.3.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enaml-extensions-{{ version }}.tar.gz
  sha256: 38871137028bab7ca93a8e2517d77f5e2dd541e1c32171df07fc3461b37a3f95

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=30.3.0
    - setuptools-scm
  run:
    - enaml
    - numpy
    - pip
    - python >=3.8
    - qscintilla2
    - qtpy

test:
  imports:
    - enamlext

about:
  home: http://github.com/gabrielcnr/enaml-extensions
  summary: Extra widgets and extensions for building UIs with Enaml
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
