{% set name = "enaml-extensions" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enaml-extensions-{{ version }}.tar.gz
  sha256: 9dfd268f75150c466f4c9e6c54b09fc4d9b85672c41d70659bb7b221a4f452d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=30.3.0
    - setuptools-scm
  run:
    - enaml
    - numpy
    - pip
    - python >=3.8
    - qscintilla2
    - qtpy

test:
  imports:
    - enamlext

about:
  home: http://github.com/gabrielcnr/enaml-extensions
  summary: Extra widgets and extensions for building UIs with Enaml
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
